import { NativeModules } from 'react-native';

const { AppGalleryIap } = NativeModules;

export const PriceType = {
  CONSUMABLE: 0,
  NON_CONSUMABLE: 1,
  AUTO_RENEWABLE: 2,
}

export const IapErrorCode = {
  ORDER_STATE_SUCCESS: 0,
  ORDER_STATE_FAILED: -1,
  ORDER_STATE_CANCEL: 60000,
  ORDER_STATE_PARAM_ERROR: 60001,
  ORDER_STATE_NET_ERROR: 60005,
  ORDER_VR_UNINSTALL_ERROR: 60020,
  ORDER_HWID_NOT_LOGIN: 60050,
  ORDER_PRODUCT_OWNED: 60051,
  ORDER_PRODUCT_NOT_OWNED: 60052,
  ORDER_PRODUCT_CONSUMED: 60053,
  ORDER_ACCOUNT_AREA_NOT_SUPPORTED: 60054,
  ORDER_NOT_ACCEPT_AGREEMENT: 60055,
  ORDER_HIGH_RISK_OPERATIONS: 60056,
}

export const ErrorCode = {
  E_NO_PRODUCTS_ADDED: "E_NO_PRODUCTS_ADDED",
  E_PURCHASE_INTENT_NO_DATA: "E_PURCHASE_INTENT_NO_DATA"
}

export default AppGalleryIap;
